# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53c42616d668faf78700d0e1717a733768f91ec51a2dc17b71ce1d3a4da546b82c55250410afbe0dad739d1e7771daafe15229775938fb44f5c5b28cbd9578aa

test:
  secret_key_base: cfdce6e7558daf72c41fa87b5ed19bb70949d41abc2b93b328044a0c0a237f40620d027f0086894b1582a16b8e62cb208ca451fa881fb999997100b080a89f3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
